/**********************************************************************
 * Extern for THREEx
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var THREEx = {
  "ARClickability": {
    "tangoPickingPointCloud": function () {}
  },
  "ArBaseControls": {
    "id": {}
  },
  "ArMarkerCloak": {
    "fragmentShader": {},
    "markerSpaceShaderFunction": {},
    "vertexShader": {}
  },
  "ArMarkerControls": function () {},
  "ArMarkerHelper": function () {},
  "ArSmoothedControls": function () {},
  "ArToolkitContext": function () {},
  "ArToolkitProfile": function () {},
  "ArToolkitSource": function () {},
  "ArVideoInWebgl": function () {},
  "ArucoContext": function () {},
  "ArucoDebug": function () {},
  "ArucoMarkerGenerator": {
    "createCanvas": function () {},
    "createImage": function () {},
    "createSVG": function () {}
  },
  "HitTestingPlane": function () {},
  "HitTestingTango": function () {},
  "addArucoDatGui": function () {}
};

THREEx.ArBaseControls.prototype = {
  "object3d": {},
  "id": {},
  "update": function () {},
  "name": function () {}
};
THREEx.ArMarkerControls.prototype = {
  "context": {},
  "parameters": {},
  "size": {},
  "type": {},
  "patternUrl": {},
  "barcodeValue": {},
  "changeMatrixMode": {},
  "minConfidence": {},
  "object3d": {},
  "updateWithModelViewMatrix": function () {},
  "name": function () {},
  "_initArtoolkit": function () {}
};
THREEx.ARClickability.prototype = {
  "computeIntersects": function () {},
  "onResize": function () {},
  "update": function () {}
};
THREEx.ArMarkerControls.prototype = {
  "_initArtoolkit": function () {},
  "_initAruco": function () {},
  "_initTango": function () {},
  "constructor": function () {},
  "dispose": function () {},
  "name": function () {},
  "updateWithModelViewMatrix": function () {}
};
THREEx.ArSmoothedControls.prototype = {
  "constructor": function () {},
  "update": function () {}
};
THREEx.ArToolkitProfile.prototype = {
  "_guessPerformanceLabel": function () {},
  "changeMatrixMode": function () {},
  "checkIfValid": function () {},
  "defaultMarker": function () {},
  "performance": function () {},
  "reset": function () {},
  "sourceImage": function () {},
  "sourceVideo": function () {},
  "sourceWebcam": function () {},
  "trackingBackend": function () {},
  "trackingMethod": function () {}
};
THREEx.ArToolkitContext.prototype = {
  "trackingBackend": {},
  "debug": {},
  "detectionMode": {},
  "matrixCodeType": {},
  "cameraParametersUrl": {},
  "maxDetectionRate": {},
  "canvasWidth": {},
  "canvasHeight": {},
  "patternRatio": {},
  "imageSmoothingEnabled": {},
  "arController": {},
  "arucoContext": {},
  "_arMarkersControls": {},
  "createDefaultCamera": function () {},
  "init": function () {},
  "update": function () {},
  "addMarker": function () {},
  "removeMarker": function () {},
  "_initArtoolkit": function () {},
  "_updateArtoolkit": function () {},
  "getProjectionMatrix": function () {},
  "_initAruco": function () {},
  "_updateAruco": function () {},
  "_initTango": function () {},
  "_updateTango": function () {},
  "updateWithModelViewMatrix": function () {},
  "getFrameData": function () {},
  "parameters": {}
};
THREEx.ArSmoothedControls.prototype = {
  "_lastLerpStepAt": {},
  "_visibleStartedAt": {},
  "_unvisibleStartedAt": {},
  "parameters": {},
  "lerpPosition": {},
  "lerpQuaternion": {},
  "lerpScale": {},
  "lerpStepDelay": {},
  "minVisibleDelay": {},
  "minUnvisibleDelay": {},
  "object3d": {},
  "wasVisible": {},
  "snapDirectlyToTarget": function () {},
  "applyOneSlerpStep": function () {}
};
THREEx.ArToolkitSource.prototype = {
  "_initSourceImage": function () {},
  "_initSourceVideo": function () {},
  "_initSourceWebcam": function () {},
  "copyElementSizeTo": function () {},
  "copySizeTo": function () {},
  "domElementHeight": function () {},
  "domElementWidth": function () {},
  "hasMobileTorch": function () {},
  "init": function () {},
  "onResize": function () {},
  "onResizeElement": function () {},
  "toggleMobileTorch": function () {},
  "ready": {},
  "domElement": {}
};
THREEx.ArVideoInWebgl.prototype = {
  "object3d": {},
  "update": function () {}
};
THREEx.ArucoContext.prototype = {
  "detect": function () {},
  "setSize": function () {},
  "updateObject3D": function () {}
};
THREEx.ArucoDebug.prototype = {
  "clear": function () {},
  "copyCVImage2ImageData": function () {},
  "drawCVImage": function () {},
  "drawContours": function () {},
  "drawContoursCandidates": function () {},
  "drawContoursContours": function () {},
  "drawContoursPolys": function () {},
  "drawDetectorGrey": function () {},
  "drawDetectorThreshold": function () {},
  "drawMarkerCorners": function () {},
  "drawMarkerIDs": function () {},
  "drawVideo": function () {},
  "setSize": function () {}
};
THREEx.HitTestingPlane.prototype = {
  "onResize": function () {},
  "renderDebug": function () {},
  "test": function () {},
  "update": function () {}
};
THREEx.HitTestingTango.prototype = {
  "test": function () {},
  "update": function () {}
};
/**********************************************************************
 * End Generated Extern for THREEx
/**********************************************************************/
